### ISSUE TITLE
about volume scene file

### ISSUE THREAD

**Issue by fenghuayumo** [Opioid/sprout#3]
I  am using your renderer to do some volume render test,Can you offer a scene file that include Participating media ?

**Comment by Opioid** [comment]
[data.zip](https://github.com/Opioid/sprout/files/2431566/data.zip)
This file should contain everything you need to render an image of the disney cloud (at 1/8 of the max voxel resolution). If you want to try different datasets you have to convert the volume data into a simple json format first, because sprout can't read openvdb files...

**Comment by fenghuayumo** [comment]
thank you your reply. look forward to your continued improvement of your renderer. it's a good work

**Comment by fenghuayumo** [comment]
I  saw your code,I don't know why you comment your Spectral tracking code,Is it not working?

**Comment by Opioid** [comment]
That file needs some cleaning up.
The spectral tracking is working, but there is still some old code from development in there, partially commented out. NOT working, however is the spectral decomposition tracking, which is disabled by default.
I hope this helps.

**Comment by fenghuayumo** [comment]
I also test use ray marching for transmission,I use rmse to quality  image,but I found that it only improve a little.The human eye can hardly see the improvement.
  how to use the clouds.raw file? your renderer seems only support .json format.  do you have other volume scene?

**Comment by Opioid** [comment]
This file specifically can also be loaded (the dimensions are hardcoded).

**Comment by Opioid** [comment]
I added the "van de Hulst" technique described in [siggraph Hyperion article](https://www.yiningkarlli.com/projects/hyperiondesign/hyperiondesign.pdf) in section _4.5.2 Similarity Relation_. The cloud rendering is roughly 10 times faster now (although results are not exactly the same).
